### PR TITLE
Add modules for fuel types

### PR DESCRIPTION
**Pull request by sierratutwiler**
Created dictionaries for multiple fuel types that are located in main TACOCAT code. Each fuel type has it's own dictionary containing thermal conductivity and melting temperature. Selection of fuel used is done manually by changing the variable Fuel_Type.

### CODE REVIEW

**Review by lcarasik — COMMENTED** [review]
DId we need the extra Py files for now?

**Comment by lcarasik** [comment]
This will address #11 as at least a framework.

**Comment by sierratutwiler** [comment]
We don't need the extra py files at the moment, all the information is located in the dictionaries in TACOCAT.

**Review by lcarasik — CHANGES_REQUESTED** [review]
Can you move the references from the individual python files to the ones in TACOCAT.py and then remove the extra files?

**Comment by sierratutwiler** [comment]
I added the references to TACOCAT but I'm unsure how to remove the extra files.

**Comment by sierratutwiler** [comment]
Extra files removed.

**Comment by sierratutwiler** [comment]
It is now specified which reference was used for each fuel.

**Review by lcarasik — APPROVED** [review]
All requested changes have been addressed.

**Comment by lcarasik** [comment]
This closes and address issue #11

**Pull request merged**
